[WIP] feat: added automatic fetching/importing of IPFS CID/URLs
livepeer/ui-kit pull request #107
Opened 2022-10-27 18:04 UTC by 0xcadams

## Description

Added automatic fetching/importing of IPFS URLs to the Player.

An IPFS [v0 or v1 CID](https://docs.ipfs.tech/concepts/content-addressing/) or URL (such as `ipfs://<CID>`, `https://<CID>.ipfs.dweb.link/` or `https://cloudflare-ipfs.com/ipfs/<CID>`, _but cannot be a directory_) can be passed as the `src` or `playbackID` to the Player, and it will automatically detect if it is a valid CID and attempt to fetch the playback info for the CID. If the API does not have an Asset with the corresponding CID, the Player will automatically attempt to import the CID from IPFS, and then play the transcoded content back.

2022-10-27 18:21 UTC, yondonfu requested changes
> If the API does not have an Asset with the corresponding CID, the Player will automatically attempt to import the CID from IPFS, and then play the transcoded content back.

Nice touch!

Just one comment about the text content of the new guide.

2022-10-27 18:21 UTC, yondonfu commented on docs/pages/examples/react/ipfs-playback.en-US.mdx
> +Now that our providers are set up, we set up file uploads with [React Dropzone](https://react-dropzone.js.org/),
Let's update the text in this doc to reflect the IPFS URL input flow instead of the dropzone file upload flow used in the "Create and Watch Asset" guide?

2022-10-27 18:39 UTC, 0xcadams commented on docs/pages/examples/react/ipfs-playback.en-US.mdx
> +Now that our providers are set up, we set up file uploads with [React Dropzone](https://react-dropzone.js.org/),
Done, yeah just hadn't gotten to docs content yet

2022-10-27 19:48 UTC, yondonfu commented on docs/pages/examples/react/ipfs-playback.en-US.mdx
> +      <CreateAndViewAsset />
```suggestion
      <IpfsPlayback />
```

^ Should this be swapped in?

2022-10-27 20:12 UTC, 0xcadams commented on packages/core/src/media/decentralizedStorage.ts
> +  )?.[1];
Created an issue for this and will resolve there
https://github.com/livepeer/livepeer.js/issues/108

2022-10-28 01:14 UTC, yondonfu approved these changes

2022-10-28 01:16 UTC, merged

2022-10-28 02:10 UTC, 0xcadams commented
This shouldn't have been merged. The build is broken in main now

2022-10-28 02:11 UTC, 0xcadams commented
Can we not demo from the preview URL?